import {
  list,
  getById,
  update,
  create,
  remove,
} from "../controllers/employees";
/**Sanjeev's employees unit test
 * 200089
 * @public */
describe("Testing employees endpoint", () => {
  /**
   * testdata-valid
   * Sanjeev Gunasekaran 200089
   * @public*/
  const testdata1 = [
    {
      first_name: "Parthivi",
      last_name: "Khullar",
      work_email: "parthivi@bassure.com",
      blood_group: "O -",
      religion: "Sikhism",
      nationality: "IND",
      aadhar_number: "88849394392",
      address1: "Somewhere in the world",
      city: "Chandigarh",
      country: "IN",
      state: "Punjab",
      zipcode: "234324",
      pre_address1: "Someplace",
      pre_city: "Chandigarh",
      pre_state: "Punjab",
      pre_country: "IN",
      pre_zipcode: "234324",
    },

    {
      first_name: "Will",
      last_name: "Smith",
      work_email: "chrisrock@bassure.com",
      blood_group: "O -",
      religion: "Atheism",
      nationality: "IND",
      aadhar_number: "88849322222",
      address1: "Somewhere in the planet",
      city: "Chennai",
      country: "IN",
      state: "Tamil Nadu",
      zipcode: "600100",
      pre_address1: "Someplace",
      pre_city: "Chennai",
      pre_state: "Tamil Nadu",
      pre_country: "IN",
      pre_zipcode: "600100",
    },
  ];
  /**
   * testdata-invalid data
   * Sanjeev Gunasekaran 200089
   * @public*/
  const testdata2 = [
    {
      employee_id: "34700112",
      first_name: "Kaithi",
      middle_name: "",
      last_name: "NumberOne",
      work_phone: "918837377777",
      work_email: "kaithi@bassure.com",
      gender: "Male",
      birthday: null,
      marital_status: null,
      blood_group: null,
      status: "Active",
      native_state: null,
      religion: null,
      nationality: null,
      aadhar_number: null,
      passport_num: null,
      pan_number: null,
      address1: null,
      address2: null,
      city: null,
      country: null,
      state: null,
      zipcode: null,
      pre_address1: null,
      pre_address2: null,
      pre_city: null,
      pre_country: null,
      pre_state: null,
      pre_zipcode: null,
      profile_pic: null,
      joined_date: null,
      height: null,
      weight: null,
      department: null,
      designation: null,
      probation: "Active",
      reason: null,
      present_and_permanent_addres_same: false,
      is_reporting_manager: false,
    },
    {
      employee_id: "200112",
      first_name: "Kaithi2134",
      middle_name: "",
      last_name: "Bawa",
      work_phone: "919844543311",
      work_email: "kaithi@bassure.com",
      gender: "Male",
      birthday: null,
      marital_status: null,
      blood_group: null,
      status: "Active",
      native_state: null,
      religion: null,
      nationality: null,
      aadhar_number: null,
      passport_num: null,
      pan_number: null,
      address1: null,
      address2: null,
      city: null,
      country: null,
      state: null,
      zipcode: null,
      pre_address1: null,
      pre_address2: null,
      pre_city: null,
      pre_country: null,
      pre_state: null,
      pre_zipcode: null,
      profile_pic: null,
      joined_date: null,
      height: null,
      weight: null,
      department: null,
      designation: null,
      probation: "Active",
      reason: null,
      present_and_permanent_addres_same: false,
      is_reporting_manager: false,
    },
    {
      employee_id: "200112",
      first_name: "Kaithi",
      middle_name: "214214",
      last_name: "Bawa",
      work_phone: "919844543311",
      work_email: "kaithi@bassure.com",
      gender: "Male",
      birthday: null,
      marital_status: null,
      blood_group: null,
      status: "Active",
      native_state: null,
      religion: null,
      nationality: null,
      aadhar_number: null,
      passport_num: null,
      pan_number: null,
      address1: null,
      address2: null,
      city: null,
      country: null,
      state: null,
      zipcode: null,
      pre_address1: null,
      pre_address2: null,
      pre_city: null,
      pre_country: null,
      pre_state: null,
      pre_zipcode: null,
      profile_pic: null,
      joined_date: null,
      height: null,
      weight: null,
      department: null,
      designation: null,
      probation: "Active",
      reason: null,
      present_and_permanent_addres_same: false,
      is_reporting_manager: false,
    },
    {
      employee_id: "200112",
      first_name: "Kaithi2134",
      middle_name: "",
      last_name: "64332fdx*&^%",
      work_phone: "919844543311",
      work_email: "kaithi@bassure.com",
      gender: "Male",
      birthday: null,
      marital_status: null,
      blood_group: null,
      status: "Active",
      native_state: null,
      religion: null,
      nationality: null,
      aadhar_number: null,
      passport_num: null,
      pan_number: null,
      address1: null,
      address2: null,
      city: null,
      country: null,
      state: null,
      zipcode: null,
      pre_address1: null,
      pre_address2: null,
      pre_city: null,
      pre_country: null,
      pre_state: null,
      pre_zipcode: null,
      profile_pic: null,
      joined_date: null,
      height: null,
      weight: null,
      department: null,
      designation: null,
      probation: "Active",
      reason: null,
      present_and_permanent_addres_same: false,
      is_reporting_manager: false,
    },
    {
      employee_id: "200112",
      first_name: "Kaithi2134",
      middle_name: "",
      last_name: "Bawa",
      work_phone: "012323232423546352928392849284298929929",
      work_email: "kaithi@bassure.com",
      gender: "Male",
      birthday: null,
      marital_status: null,
      blood_group: null,
      status: "Active",
      native_state: null,
      religion: null,
      nationality: null,
      aadhar_number: null,
      passport_num: null,
      pan_number: null,
      address1: null,
      address2: null,
      city: null,
      country: null,
      state: null,
      zipcode: null,
      pre_address1: null,
      pre_address2: null,
      pre_city: null,
      pre_country: null,
      pre_state: null,
      pre_zipcode: null,
      profile_pic: null,
      joined_date: null,
      height: null,
      weight: null,
      department: null,
      designation: null,
      probation: "Active",
      reason: null,
      present_and_permanent_addres_same: false,
      is_reporting_manager: false,
    },
    {
      employee_id: "200112",
      first_name: "Kaithi2134",
      middle_name: "",
      last_name: "Bawa",
      work_phone: "919844543311",
      work_email: "kaith*^$%&^*",
      gender: "Male",
      birthday: null,
      marital_status: null,
      blood_group: null,
      status: "Active",
      native_state: null,
      religion: null,
      nationality: null,
      aadhar_number: null,
      passport_num: null,
      pan_number: null,
      address1: null,
      address2: null,
      city: null,
      country: null,
      state: null,
      zipcode: null,
      pre_address1: null,
      pre_address2: null,
      pre_city: null,
      pre_country: null,
      pre_state: null,
      pre_zipcode: null,
      profile_pic: null,
      joined_date: null,
      height: null,
      weight: null,
      department: null,
      designation: null,
      probation: "Active",
      reason: null,
      present_and_permanent_addres_same: false,
      is_reporting_manager: false,
    },
    {
      employee_id: "200112",
      first_name: "Kaithi2134",
      middle_name: "",
      last_name: "Bawa",
      work_phone: "919844543311",
      work_email: "kaithi@bassure.com",
      gender: "Sosmdosm",
      birthday: null,
      marital_status: null,
      blood_group: null,
      status: "Active",
      native_state: null,
      religion: null,
      nationality: null,
      aadhar_number: null,
      passport_num: null,
      pan_number: null,
      address1: null,
      address2: null,
      city: null,
      country: null,
      state: null,
      zipcode: null,
      pre_address1: null,
      pre_address2: null,
      pre_city: null,
      pre_country: null,
      pre_state: null,
      pre_zipcode: null,
      profile_pic: null,
      joined_date: null,
      height: null,
      weight: null,
      department: null,
      designation: null,
      probation: "Active",
      reason: null,
      present_and_permanent_addres_same: false,
      is_reporting_manager: false,
    },
    {
      employee_id: "200112",
      first_name: "Kaithi2134",
      middle_name: "",
      last_name: "Bawa",
      work_phone: "919844543311",
      work_email: "kaithi@bassure.com",
      gender: "Male",
      birthday: "msddskmoospspspsp",
      marital_status: null,
      blood_group: null,
      status: "Active",
      native_state: null,
      religion: null,
      nationality: null,
      aadhar_number: null,
      passport_num: null,
      pan_number: null,
      address1: null,
      address2: null,
      city: null,
      country: null,
      state: null,
      zipcode: null,
      pre_address1: null,
      pre_address2: null,
      pre_city: null,
      pre_country: null,
      pre_state: null,
      pre_zipcode: null,
      profile_pic: null,
      joined_date: null,
      height: null,
      weight: null,
      department: null,
      designation: null,
      probation: "Active",
      reason: null,
      present_and_permanent_addres_same: false,
      is_reporting_manager: false,
    },
    {
      employee_id: "200112",
      first_name: "Kaithi2134",
      middle_name: "",
      last_name: "Bawa",
      work_phone: "919844543311",
      work_email: "kaithi@bassure.com",
      gender: "Male",
      birthday: null,
      marital_status: "Anyonedknsdisnd",
      blood_group: null,
      status: "Active",
      native_state: null,
      religion: null,
      nationality: null,
      aadhar_number: null,
      passport_num: null,
      pan_number: null,
      address1: null,
      address2: null,
      city: null,
      country: null,
      state: null,
      zipcode: null,
      pre_address1: null,
      pre_address2: null,
      pre_city: null,
      pre_country: null,
      pre_state: null,
      pre_zipcode: null,
      profile_pic: null,
      joined_date: null,
      height: null,
      weight: null,
      department: null,
      designation: null,
      probation: "Active",
      reason: null,
      present_and_permanent_addres_same: false,
      is_reporting_manager: false,
    },
    {
      employee_id: "200112",
      first_name: "Kaithi2134",
      middle_name: "",
      last_name: "Bawa",
      work_phone: "919844543311",
      work_email: "kaithi@bassure.com",
      gender: "Male",
      birthday: null,
      marital_status: null,
      blood_group: "Ha-BB$$",
      status: "Active",
      native_state: null,
      religion: null,
      nationality: null,
      aadhar_number: null,
      passport_num: null,
      pan_number: null,
      address1: null,
      address2: null,
      city: null,
      country: null,
      state: null,
      zipcode: null,
      pre_address1: null,
      pre_address2: null,
      pre_city: null,
      pre_country: null,
      pre_state: null,
      pre_zipcode: null,
      profile_pic: null,
      joined_date: null,
      height: null,
      weight: null,
      department: null,
      designation: null,
      probation: "Active",
      reason: null,
      present_and_permanent_addres_same: false,
      is_reporting_manager: false,
    },
    {
      employee_id: "200112",
      first_name: "Kaithi2134",
      middle_name: "",
      last_name: "Bawa",
      work_phone: "919844543311",
      work_email: "kaithi@bassure.com",
      gender: "Male",
      birthday: null,
      marital_status: null,
      blood_group: "B +",
      status: "Skraaaaaa",
      native_state: null,
      religion: null,
      nationality: null,
      aadhar_number: null,
      passport_num: null,
      pan_number: null,
      address1: null,
      address2: null,
      city: null,
      country: null,
      state: null,
      zipcode: null,
      pre_address1: null,
      pre_address2: null,
      pre_city: null,
      pre_country: null,
      pre_state: null,
      pre_zipcode: null,
      profile_pic: null,
      joined_date: null,
      height: null,
      weight: null,
      department: null,
      designation: null,
      probation: "Active",
      reason: null,
      present_and_permanent_addres_same: false,
      is_reporting_manager: false,
    },
    {
      employee_id: "200112",
      first_name: "Kaithi2134",
      middle_name: "",
      last_name: "Bawa",
      work_phone: "919844543311",
      work_email: "kaithi@bassure.com",
      gender: "Male",
      birthday: null,
      marital_status: null,
      blood_group: "B +",
      status: "Active",
      native_state: 9876.54,
      religion: null,
      nationality: null,
      aadhar_number: null,
      passport_num: null,
      pan_number: null,
      address1: null,
      address2: null,
      city: null,
      country: null,
      state: null,
      zipcode: null,
      pre_address1: null,
      pre_address2: null,
      pre_city: null,
      pre_country: null,
      pre_state: null,
      pre_zipcode: null,
      profile_pic: null,
      joined_date: null,
      height: null,
      weight: null,
      department: null,
      designation: null,
      probation: "Active",
      reason: null,
      present_and_permanent_addres_same: false,
      is_reporting_manager: false,
    },
    {
      employee_id: "200112",
      first_name: "Kaithi2134",
      middle_name: "",
      last_name: "Bawa",
      work_phone: "919844543311",
      work_email: "kaithi@bassure.com",
      gender: "Male",
      birthday: null,
      marital_status: null,
      blood_group: "B +",
      status: "Active",
      native_state: "Tamil Nadu",
      religion: "Somethingism",
      nationality: null,
      aadhar_number: null,
      passport_num: null,
      pan_number: null,
      address1: null,
      address2: null,
      city: null,
      country: null,
      state: null,
      zipcode: null,
      pre_address1: null,
      pre_address2: null,
      pre_city: null,
      pre_country: null,
      pre_state: null,
      pre_zipcode: null,
      profile_pic: null,
      joined_date: null,
      height: null,
      weight: null,
      department: null,
      designation: null,
      probation: "Active",
      reason: null,
      present_and_permanent_addres_same: false,
      is_reporting_manager: false,
    },
    {
      employee_id: "200112",
      first_name: "Kaithi2134",
      middle_name: "",
      last_name: "Bawa",
      work_phone: "919844543311",
      work_email: "kaithi@bassure.com",
      gender: "Male",
      birthday: null,
      marital_status: null,
      blood_group: "B +",
      status: "Active",
      native_state: "Tamil Nadu",
      religion: "Atheism",
      nationality: 325.2523,
      aadhar_number: null,
      passport_num: null,
      pan_number: null,
      address1: null,
      address2: null,
      city: null,
      country: null,
      state: null,
      zipcode: null,
      pre_address1: null,
      pre_address2: null,
      pre_city: null,
      pre_country: null,
      pre_state: null,
      pre_zipcode: null,
      profile_pic: null,
      joined_date: null,
      height: null,
      weight: null,
      department: null,
      designation: null,
      probation: "Active",
      reason: null,
      present_and_permanent_addres_same: false,
      is_reporting_manager: false,
    },
    {
      employee_id: "200112",
      first_name: "Kaithi2134",
      middle_name: "",
      last_name: "Bawa",
      work_phone: "919844543311",
      work_email: "kaithi@bassure.com",
      gender: "Male",
      birthday: null,
      marital_status: null,
      blood_group: "B +",
      status: "Active",
      native_state: "Tamil Nadu",
      religion: "Atheism",
      nationality: 325.2523,
      aadhar_number: null,
      passport_num: null,
      pan_number: null,
      address1: null,
      address2: null,
      city: null,
      country: null,
      state: null,
      zipcode: null,
      pre_address1: null,
      pre_address2: null,
      pre_city: null,
      pre_country: null,
      pre_state: null,
      pre_zipcode: null,
      profile_pic: null,
      joined_date: null,
      height: null,
      weight: null,
      department: null,
      designation: null,
      probation: "Active",
      reason: null,
      present_and_permanent_addres_same: false,
      is_reporting_manager: false,
    },
    {
      employee_id: "200112",
      first_name: "Kaithi2134",
      middle_name: "",
      last_name: "Bawa",
      work_phone: "919844543311",
      work_email: "kaithi@bassure.com",
      gender: "Male",
      birthday: null,
      marital_status: null,
      blood_group: "B +",
      status: "Active",
      native_state: "Tamil Nadu",
      religion: "Atheism",
      nationality: "Antartica",
      aadhar_number: 134235.351,
      passport_num: null,
      pan_number: null,
      address1: null,
      address2: null,
      city: null,
      country: null,
      state: null,
      zipcode: null,
      pre_address1: null,
      pre_address2: null,
      pre_city: null,
      pre_country: null,
      pre_state: null,
      pre_zipcode: null,
      profile_pic: null,
      joined_date: null,
      height: null,
      weight: null,
      department: null,
      designation: null,
      probation: "Active",
      reason: null,
      present_and_permanent_addres_same: false,
      is_reporting_manager: false,
    },
    {
      employee_id: "200112",
      first_name: "Kaithi2134",
      middle_name: "",
      last_name: "Bawa",
      work_phone: "919844543311",
      work_email: "kaithi@bassure.com",
      gender: "Male",
      birthday: null,
      marital_status: null,
      blood_group: "B +",
      status: "Active",
      native_state: "Tamil Nadu",
      religion: "Atheism",
      nationality: "Antartica",
      aadhar_number: null,
      passport_num: 2464264262452,
      pan_number: null,
      address1: null,
      address2: null,
      city: null,
      country: null,
      state: null,
      zipcode: null,
      pre_address1: null,
      pre_address2: null,
      pre_city: null,
      pre_country: null,
      pre_state: null,
      pre_zipcode: null,
      profile_pic: null,
      joined_date: null,
      height: null,
      weight: null,
      department: null,
      designation: null,
      probation: "Active",
      reason: null,
      present_and_permanent_addres_same: false,
      is_reporting_manager: false,
    },
    {
      employee_id: "200112",
      first_name: "Kaithi2134",
      middle_name: "",
      last_name: "Bawa",
      work_phone: "919844543311",
      work_email: "kaithi@bassure.com",
      gender: "Male",
      birthday: null,
      marital_status: null,
      blood_group: "B +",
      status: "Active",
      native_state: "Tamil Nadu",
      religion: "Atheism",
      nationality: "Antartica",
      aadhar_number: null,
      passport_num: null,
      pan_number: 3948395992.53,
      address1: null,
      address2: null,
      city: null,
      country: null,
      state: null,
      zipcode: null,
      pre_address1: null,
      pre_address2: null,
      pre_city: null,
      pre_country: null,
      pre_state: null,
      pre_zipcode: null,
      profile_pic: null,
      joined_date: null,
      height: null,
      weight: null,
      department: null,
      designation: null,
      probation: "Active",
      reason: null,
      present_and_permanent_addres_same: false,
      is_reporting_manager: false,
    },
    {
      employee_id: "200112",
      first_name: "Kaithi2134",
      middle_name: "",
      last_name: "Bawa",
      work_phone: "919844543311",
      work_email: "kaithi@bassure.com",
      gender: "Male",
      birthday: null,
      marital_status: null,
      blood_group: "B +",
      status: "Active",
      native_state: "Tamil Nadu",
      religion: "Atheism",
      nationality: "Antartica",
      aadhar_number: null,
      passport_num: null,
      pan_number: null,
      address1: 32985248.3532,
      address2: 42542542532.245325,
      city: null,
      country: null,
      state: null,
      zipcode: null,
      pre_address1: null,
      pre_address2: null,
      pre_city: null,
      pre_country: null,
      pre_state: null,
      pre_zipcode: null,
      profile_pic: null,
      joined_date: null,
      height: null,
      weight: null,
      department: null,
      designation: null,
      probation: "Active",
      reason: null,
      present_and_permanent_addres_same: false,
      is_reporting_manager: false,
    },
    {
      employee_id: "200112",
      first_name: "Kaithi2134",
      middle_name: "",
      last_name: "Bawa",
      work_phone: "919844543311",
      work_email: "kaithi@bassure.com",
      gender: "Male",
      birthday: null,
      marital_status: null,
      blood_group: "B +",
      status: "Active",
      native_state: "Tamil Nadu",
      religion: "Atheism",
      nationality: "Antartica",
      aadhar_number: null,
      passport_num: null,
      pan_number: null,
      address1: null,
      address2: null,
      city: "Ho Chi Minh City124214",
      country: null,
      state: null,
      zipcode: null,
      pre_address1: null,
      pre_address2: null,
      pre_city: null,
      pre_country: null,
      pre_state: null,
      pre_zipcode: null,
      profile_pic: null,
      joined_date: null,
      height: null,
      weight: null,
      department: null,
      designation: null,
      probation: "Active",
      reason: null,
      present_and_permanent_addres_same: false,
      is_reporting_manager: false,
    },
    {
      employee_id: "200112",
      first_name: "Kaithi2134",
      middle_name: "",
      last_name: "Bawa",
      work_phone: "919844543311",
      work_email: "kaithi@bassure.com",
      gender: "Male",
      birthday: null,
      marital_status: null,
      blood_group: "B +",
      status: "Active",
      native_state: "Tamil Nadu",
      religion: "Atheism",
      nationality: "Antartica",
      aadhar_number: null,
      passport_num: null,
      pan_number: null,
      address1: null,
      address2: null,
      city: "Ho Chi Minh City",
      country: "MARSDA",
      state: null,
      zipcode: null,
      pre_address1: null,
      pre_address2: null,
      pre_city: null,
      pre_country: null,
      pre_state: null,
      pre_zipcode: null,
      profile_pic: null,
      joined_date: null,
      height: null,
      weight: null,
      department: null,
      designation: null,
      probation: "Active",
      reason: null,
      present_and_permanent_addres_same: false,
      is_reporting_manager: false,
    },
    {
      employee_id: "200112",
      first_name: "Kaithi2134",
      middle_name: "",
      last_name: "Bawa",
      work_phone: "919844543311",
      work_email: "kaithi@bassure.com",
      gender: "Male",
      birthday: null,
      marital_status: null,
      blood_group: "B +",
      status: "Active",
      native_state: "Tamil Nadu",
      religion: "Atheism",
      nationality: "Antartica",
      aadhar_number: null,
      passport_num: null,
      pan_number: null,
      address1: null,
      address2: null,
      city: "Ho Chi Minh City",
      country: "IN",
      state: true,
      zipcode: null,
      pre_address1: null,
      pre_address2: null,
      pre_city: null,
      pre_country: null,
      pre_state: null,
      pre_zipcode: null,
      profile_pic: null,
      joined_date: null,
      height: null,
      weight: null,
      department: null,
      designation: null,
      probation: "Active",
      reason: null,
      present_and_permanent_addres_same: false,
      is_reporting_manager: false,
    },
    {
      employee_id: "200112",
      first_name: "Kaithi2134",
      middle_name: "",
      last_name: "Bawa",
      work_phone: "919844543311",
      work_email: "kaithi@bassure.com",
      gender: "Male",
      birthday: null,
      marital_status: null,
      blood_group: "B +",
      status: "Active",
      native_state: "Tamil Nadu",
      religion: "Atheism",
      nationality: "Antartica",
      aadhar_number: null,
      passport_num: null,
      pan_number: null,
      address1: null,
      address2: null,
      city: "Ho Chi Minh City",
      country: "IN",
      state: null,
      zipcode: 324.223,
      pre_address1: null,
      pre_address2: null,
      pre_city: null,
      pre_country: null,
      pre_state: null,
      pre_zipcode: null,
      profile_pic: null,
      joined_date: null,
      height: null,
      weight: null,
      department: null,
      designation: null,
      probation: "Active",
      reason: null,
      present_and_permanent_addres_same: false,
      is_reporting_manager: false,
    },
    {
      employee_id: "200112",
      first_name: "Kaithi2134",
      middle_name: "",
      last_name: "Bawa",
      work_phone: "919844543311",
      work_email: "kaithi@bassure.com",
      gender: "Male",
      birthday: null,
      marital_status: null,
      blood_group: "B +",
      status: "Active",
      native_state: "Tamil Nadu",
      religion: "Atheism",
      nationality: "Antartica",
      aadhar_number: null,
      passport_num: null,
      pan_number: null,
      address1: null,
      address2: null,
      city: "Ho Chi Minh City",
      country: "IN",
      state: null,
      zipcode: null,
      pre_address1: false,
      pre_address2: null,
      pre_city: null,
      pre_country: null,
      pre_state: null,
      pre_zipcode: null,
      profile_pic: null,
      joined_date: null,
      height: null,
      weight: null,
      department: null,
      designation: null,
      probation: "Active",
      reason: null,
      present_and_permanent_addres_same: false,
      is_reporting_manager: false,
    },
    {
      employee_id: "200112",
      first_name: "Kaithi2134",
      middle_name: "",
      last_name: "Bawa",
      work_phone: "919844543311",
      work_email: "kaithi@bassure.com",
      gender: "Male",
      birthday: null,
      marital_status: null,
      blood_group: "B +",
      status: "Active",
      native_state: "Tamil Nadu",
      religion: "Atheism",
      nationality: "Antartica",
      aadhar_number: null,
      passport_num: null,
      pan_number: null,
      address1: null,
      address2: null,
      city: "Ho Chi Minh City",
      country: "IN",
      state: null,
      zipcode: null,
      pre_address1: null,
      pre_address2: false,
      pre_city: null,
      pre_country: null,
      pre_state: null,
      pre_zipcode: null,
      profile_pic: null,
      joined_date: null,
      height: null,
      weight: null,
      department: null,
      designation: null,
      probation: "Active",
      reason: null,
      present_and_permanent_addres_same: false,
      is_reporting_manager: false,
    },
    {
      employee_id: "200112",
      first_name: "Kaithi2134",
      middle_name: "",
      last_name: "Bawa",
      work_phone: "919844543311",
      work_email: "kaithi@bassure.com",
      gender: "Male",
      birthday: null,
      marital_status: null,
      blood_group: "B +",
      status: "Active",
      native_state: "Tamil Nadu",
      religion: "Atheism",
      nationality: "Antartica",
      aadhar_number: null,
      passport_num: null,
      pan_number: null,
      address1: null,
      address2: null,
      city: "Ho Chi Minh City",
      country: "IN",
      state: null,
      zipcode: null,
      pre_address1: null,
      pre_address2: null,
      pre_city: "3722",
      pre_country: null,
      pre_state: null,
      pre_zipcode: null,
      profile_pic: null,
      joined_date: null,
      height: null,
      weight: null,
      department: null,
      designation: null,
      probation: "Active",
      reason: null,
      present_and_permanent_addres_same: false,
      is_reporting_manager: false,
    },
    {
      employee_id: "200112",
      first_name: "Kaithi2134",
      middle_name: "",
      last_name: "Bawa",
      work_phone: "919844543311",
      work_email: "kaithi@bassure.com",
      gender: "Male",
      birthday: null,
      marital_status: null,
      blood_group: "B +",
      status: "Active",
      native_state: "Tamil Nadu",
      religion: "Atheism",
      nationality: "Antartica",
      aadhar_number: null,
      passport_num: null,
      pan_number: null,
      address1: null,
      address2: null,
      city: "Ho Chi Minh City",
      country: "IN",
      state: null,
      zipcode: null,
      pre_address1: null,
      pre_address2: null,
      pre_city: null,
      pre_country: 345.3,
      pre_state: null,
      pre_zipcode: null,
      profile_pic: null,
      joined_date: null,
      height: null,
      weight: null,
      department: null,
      designation: null,
      probation: "Active",
      reason: null,
      present_and_permanent_addres_same: false,
      is_reporting_manager: false,
    },
    {
      employee_id: "200112",
      first_name: "Kaithi2134",
      middle_name: "",
      last_name: "Bawa",
      work_phone: "919844543311",
      work_email: "kaithi@bassure.com",
      gender: "Male",
      birthday: null,
      marital_status: null,
      blood_group: "B +",
      status: "Active",
      native_state: "Tamil Nadu",
      religion: "Atheism",
      nationality: "Antartica",
      aadhar_number: null,
      passport_num: null,
      pan_number: null,
      address1: null,
      address2: null,
      city: "Ho Chi Minh City",
      country: "IN",
      state: null,
      zipcode: null,
      pre_address1: null,
      pre_address2: null,
      pre_city: null,
      pre_country: null,
      pre_state: true,
      pre_zipcode: null,
      profile_pic: null,
      joined_date: null,
      height: null,
      weight: null,
      department: null,
      designation: null,
      probation: "Active",
      reason: null,
      present_and_permanent_addres_same: false,
      is_reporting_manager: false,
    },
    {
      employee_id: "200112",
      first_name: "Kaithi2134",
      middle_name: "",
      last_name: "Bawa",
      work_phone: "919844543311",
      work_email: "kaithi@bassure.com",
      gender: "Male",
      birthday: null,
      marital_status: null,
      blood_group: "B +",
      status: "Active",
      native_state: "Tamil Nadu",
      religion: "Atheism",
      nationality: "Antartica",
      aadhar_number: null,
      passport_num: null,
      pan_number: null,
      address1: null,
      address2: null,
      city: "Ho Chi Minh City",
      country: "IN",
      state: null,
      zipcode: null,
      pre_address1: null,
      pre_address2: null,
      pre_city: null,
      pre_country: null,
      pre_state: null,
      pre_zipcode: true,
      profile_pic: null,
      joined_date: null,
      height: null,
      weight: null,
      department: null,
      designation: null,
      probation: "Active",
      reason: null,
      present_and_permanent_addres_same: false,
      is_reporting_manager: false,
    },
    {
      employee_id: "200112",
      first_name: "Kaithi2134",
      middle_name: "",
      last_name: "Bawa",
      work_phone: "919844543311",
      work_email: "kaithi@bassure.com",
      gender: "Male",
      birthday: null,
      marital_status: null,
      blood_group: "B +",
      status: "Active",
      native_state: "Tamil Nadu",
      religion: "Atheism",
      nationality: "Antartica",
      aadhar_number: null,
      passport_num: null,
      pan_number: null,
      address1: null,
      address2: null,
      city: "Ho Chi Minh City",
      country: "IN",
      state: null,
      zipcode: null,
      pre_address1: null,
      pre_address2: null,
      pre_city: null,
      pre_country: null,
      pre_state: null,
      pre_zipcode: null,
      joined_date: "NSJNJNJDJDS",
      height: null,
      weight: null,
      department: null,
      designation: null,
      probation: "Active",
      reason: null,
      present_and_permanent_addres_same: false,
      is_reporting_manager: false,
    },
    {
      employee_id: "200112",
      first_name: "Kaithi2134",
      middle_name: "",
      last_name: "Bawa",
      work_phone: "919844543311",
      work_email: "kaithi@bassure.com",
      gender: "Male",
      birthday: null,
      marital_status: null,
      blood_group: "B +",
      status: "Active",
      native_state: "Tamil Nadu",
      religion: "Atheism",
      nationality: "Antartica",
      aadhar_number: null,
      passport_num: null,
      pan_number: null,
      address1: null,
      address2: null,
      city: "Ho Chi Minh City",
      country: "IN",
      state: null,
      zipcode: null,
      pre_address1: null,
      pre_address2: null,
      pre_city: null,
      pre_country: null,
      pre_state: null,
      pre_zipcode: null,
      joined_date: null,
      height: 9000,
      weight: null,
      department: null,
      designation: null,
      probation: "Active",
      reason: null,
      present_and_permanent_addres_same: false,
      is_reporting_manager: false,
    },
    {
      employee_id: "200112",
      first_name: "Kaithi2134",
      middle_name: "",
      last_name: "Bawa",
      work_phone: "919844543311",
      work_email: "kaithi@bassure.com",
      gender: "Male",
      birthday: null,
      marital_status: null,
      blood_group: "B +",
      status: "Active",
      native_state: "Tamil Nadu",
      religion: "Atheism",
      nationality: "Antartica",
      aadhar_number: null,
      passport_num: null,
      pan_number: null,
      address1: null,
      address2: null,
      city: "Ho Chi Minh City",
      country: "IN",
      state: null,
      zipcode: null,
      pre_address1: null,
      pre_address2: null,
      pre_city: null,
      pre_country: null,
      pre_state: null,
      pre_zipcode: null,
      joined_date: null,
      height: null,
      weight: 1200,
      department: null,
      designation: null,
      probation: "Active",
      reason: null,
      present_and_permanent_addres_same: false,
      is_reporting_manager: false,
    },
    {
      employee_id: "200112",
      first_name: "Kaithi2134",
      middle_name: "",
      last_name: "Bawa",
      work_phone: "919844543311",
      work_email: "kaithi@bassure.com",
      gender: "Male",
      birthday: null,
      marital_status: null,
      blood_group: "B +",
      status: "Active",
      native_state: "Tamil Nadu",
      religion: "Atheism",
      nationality: "Antartica",
      aadhar_number: null,
      passport_num: null,
      pan_number: null,
      address1: null,
      address2: null,
      city: "Ho Chi Minh City",
      country: "IN",
      state: null,
      zipcode: null,
      pre_address1: null,
      pre_address2: null,
      pre_city: null,
      pre_country: null,
      pre_state: null,
      pre_zipcode: null,
      joined_date: null,
      height: null,
      weight: null,
      department: 1,
      designation: null,
      probation: "Active",
      reason: null,
      present_and_permanent_addres_same: false,
      is_reporting_manager: false,
    },
    {
      employee_id: "200112",
      first_name: "Kaithi2134",
      middle_name: "",
      last_name: "Bawa",
      work_phone: "919844543311",
      work_email: "kaithi@bassure.com",
      gender: "Male",
      birthday: null,
      marital_status: null,
      blood_group: "B +",
      status: "Active",
      native_state: "Tamil Nadu",
      religion: "Atheism",
      nationality: "Antartica",
      aadhar_number: null,
      passport_num: null,
      pan_number: null,
      address1: null,
      address2: null,
      city: "Ho Chi Minh City",
      country: "IN",
      state: null,
      zipcode: null,
      pre_address1: null,
      pre_address2: null,
      pre_city: null,
      pre_country: null,
      pre_state: null,
      pre_zipcode: null,
      joined_date: null,
      height: null,
      weight: null,
      department: null,
      designation: 0.232,
      probation: "Active",
      reason: null,
      present_and_permanent_addres_same: false,
      is_reporting_manager: false,
    },
    {
      employee_id: "200112",
      first_name: "Kaithi2134",
      middle_name: "",
      last_name: "Bawa",
      work_phone: "919844543311",
      work_email: "kaithi@bassure.com",
      gender: "Male",
      birthday: null,
      marital_status: null,
      blood_group: "B +",
      status: "Active",
      native_state: "Tamil Nadu",
      religion: "Atheism",
      nationality: "Antartica",
      aadhar_number: null,
      passport_num: null,
      pan_number: null,
      address1: null,
      address2: null,
      city: "Ho Chi Minh City",
      country: "IN",
      state: null,
      zipcode: null,
      pre_address1: null,
      pre_address2: null,
      pre_city: null,
      pre_country: null,
      pre_state: null,
      pre_zipcode: null,
      joined_date: null,
      height: null,
      weight: null,
      department: null,
      designation: null,
      probation: "Idontknow",
      reason: null,
      present_and_permanent_addres_same: false,
      is_reporting_manager: false,
    },
    {
      employee_id: "200112",
      first_name: "Kaithi2134",
      middle_name: "",
      last_name: "Bawa",
      work_phone: "919844543311",
      work_email: "kaithi@bassure.com",
      gender: "Male",
      birthday: null,
      marital_status: null,
      blood_group: "B +",
      status: "Active",
      native_state: "Tamil Nadu",
      religion: "Atheism",
      nationality: "Antartica",
      aadhar_number: null,
      passport_num: null,
      pan_number: null,
      address1: null,
      address2: null,
      city: "Ho Chi Minh City",
      country: "IN",
      state: null,
      zipcode: null,
      pre_address1: null,
      pre_address2: null,
      pre_city: null,
      pre_country: null,
      pre_state: null,
      pre_zipcode: null,
      joined_date: null,
      height: null,
      weight: null,
      department: null,
      designation: null,
      probation: "Active",
      present_and_permanent_addres_same: "jajajaja",
      is_reporting_manager: false,
    },
    {
      employee_id: "200112",
      first_name: "Kaithi2134",
      middle_name: "",
      last_name: "Bawa",
      work_phone: "919844543311",
      work_email: "kaithi@bassure.com",
      gender: "Male",
      birthday: null,
      marital_status: null,
      blood_group: "B +",
      status: "Active",
      native_state: "Tamil Nadu",
      religion: "Atheism",
      nationality: "Antartica",
      aadhar_number: null,
      passport_num: null,
      pan_number: null,
      address1: null,
      address2: null,
      city: "Ho Chi Minh City",
      country: "IN",
      state: null,
      zipcode: null,
      pre_address1: null,
      pre_address2: null,
      pre_city: null,
      pre_country: null,
      pre_state: null,
      pre_zipcode: null,
      joined_date: null,
      height: null,
      weight: null,
      department: null,
      designation: null,
      probation: "Active",
      present_and_permanent_addres_same: true,
      is_reporting_manager: null,
    },
  ];
  /**
   * testdata-business logic fail data
   * Sanjeev Gunasekaran 200089
   * @public*/
  const testdata3 = [];

    test("GetAll: ", async () => {
      let result = await list();
      expect(result.code).toBe(200);
    });
    test("GetById: ", async () => {
      let result = await getById(1);
      expect(result.code).toBe(200);
    });

  //   for (let i in testdata1) {
  //     test("Create (correct data): ", async () => {
  //       let result = await create(testdata1[i]);
  //       expect(result.code).toBe(200);
  //     });
  //   }

  //   test("Update (correct data): ", async () => {
  //     let result = await update(testdata1[0],testdata1.indexOf(testdata1[0]));
  //     expect(result.code).toBe(200);
  //   });

//   test("Delete: ", async () => {
//     let result = await remove(testdata1.indexOf(testdata1[1]));
//     expect(result.code).toBe(200);
//   });

  //   for (let i in testdata2) {
  //     test("Create (invalid data): ", async () => {
  //       let result = await create(testdata2[i]);
  //       expect(result.code).toBe(422);
  //     });
  //   }

  //   for (let i in testdata2) {
  //     test("Edit (invalid data): ", async () => {
  //       let result = await update(testdata2[i], testdata2.indexOf(testdata2[i]));
  //       expect(result.code).toBe(422);
  //     });
  //   }
});
////2022-07-2022/////
